# Generated by Django 3.0.9 on 2020-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid_tweet_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('keyword', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=100)),
                ('entities', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
