# Generated by Django 3.1.1 on 2020-09-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(db_column='author', max_length=200),
        ),
    ]
