# Generated by Django 3.1.1 on 2020-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0002_auto_20200907_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.FloatField(),
        ),
    ]
