# Generated by Django 3.1.1 on 2020-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0004_auto_20200908_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
    ]
