# Generated by Django 3.1.1 on 2020-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0005_post_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='identifier',
            field=models.IntegerField(),
        ),
    ]
