# Generated by Django 3.1.1 on 2020-10-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0005_post_imageurl'),
        ('depandemic', '0006_auto_20200929_1452'),
    ]

    operations = [
    ]
